import {
  Content,
  Heading,
  Line,
  Section,
} from "@heather-turano-coaching/components";
import React from "react";

import { Layout, SEO } from "../components";

const IndexPage = () => {
  return (
    <Layout>
      <SEO
        title="Privacy Policy"
        description="Mindful Movement 100's privacy policy"
      />
      <Section styleType="blank">
        <Heading fontSize="h1" fontFamily="Playfair Display">
          Privacy Policy
        </Heading>
        <br />
        <Content>
          <p>Effective date: 06/05/2020</p>
          <ol type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Introduction</span>
                </strong>
              </p>
            </li>
          </ol>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              Welcome to <strong>HEATHER TURANO COACHING, LLC</strong>
            </p>
            <p>
              HEATHER TURANO COACHING, LLC (“us”, “we”, or “our”)
              operates livelifemindful.com (hereinafter referred to as “
              <strong>Service</strong>”).
            </p>
            <p>
              Our Privacy Policy governs your visit to livelifemindful.com, and
              explains how we collect, safeguard and disclose information that
              results from your use of our Service.
            </p>
            <p>
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions.
            </p>
            <p>
              Our Terms and Conditions (“<strong>Terms</strong>”) govern all use
              of our Service and together with the Privacy Policy constitutes
              your agreement with us (“<strong>agreement</strong>”).
            </p>
          </blockquote>
          <ol start="2" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Definitions</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              <strong>SERVICE </strong>means the livelifemindful.com
              website operated by HEATHER TURANO COACHING, LLC
            </p>
            <p>
              <strong>PERSONAL DATA</strong> means data about a living
              individual who can be identified from those data (or from those
              and other information either in our possession or likely to come
              into our possession).
            </p>
            <p>
              <strong>USAGE DATA</strong> is data collected automatically either
              generated by the use of Service or from Service infrastructure
              itself (for example, the duration of a page visit).
            </p>
            <p>
              <strong>COOKIES</strong> are small files stored on your device
              (computer or mobile device).
            </p>
            <p>
              <strong>DATA CONTROLLER</strong> means a natural or legal person
              who (either alone or jointly or in common with other persons)
              determines the purposes for which and the manner in which any
              personal data are, or are to be, processed. For the purpose of
              this Privacy Policy, we are a Data Controller of your data.
            </p>
            <p>
              <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
              natural or legal person who processes the data on behalf of the
              Data Controller. We may use the services of various Service
              Providers in order to process your data more effectively.
            </p>
            <p>
              <strong>DATA SUBJECT </strong>is any living individual who is the
              subject of Personal Data.
            </p>
            <p>
              <strong>THE USER </strong>is the individual using our Service. The
              User corresponds to the Data Subject, who is the subject of
              Personal Data.
            </p>
          </blockquote>
          <ol start="3" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">
                    Information Collection and Use
                  </span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>
          </blockquote>
          <ol start="4" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Types of Data Collected</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              <strong>Personal Data</strong>
            </p>
            <p>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“<strong>Personal Data</strong>”). Personally
              identifiable information may include, but is not limited to:
            </p>
          </blockquote>
          <ol type="a">
            <li>
              <p>Email address</p>
            </li>
            <li>
              <p>First name and last name</p>
            </li>
            <li>
              <p>Phone number</p>
            </li>
            <li>
              <p>Address, State, Province, ZIP/Postal code, City</p>
            </li>
            <li>
              <p>Cookies and Usage Data</p>
            </li>
          </ol>
          <blockquote>
            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link
              or by emailing at support@heatherturanocoaching.com.
            </p>
            <p>
              <strong>Usage Data</strong>
            </p>
            <p>
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through a
              mobile device (“<strong>Usage Data</strong>”).
            </p>
            <p>
              This Usage Data may include information such as your computer's
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that you visit, the time and
              date of your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </p>
            <p>
              When you access Service with a mobile device, this Usage Data may
              include information such as the type of mobile device you use,
              your mobile device unique ID, the IP address of your mobile
              device, your mobile operating system, the type of mobile Internet
              browser you use, unique device identifiers and other diagnostic
              data.
            </p>
            <p>
              <em>
                <strong>Tracking Cookies Data</strong>
              </em>
            </p>
            <p>
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information.
            </p>
            <p>
              Cookies are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyze our Service.
            </p>
            <p>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </p>
            <p>Examples of Cookies we use:</p>
          </blockquote>
          <ol type="a">
            <li>
              <p>
                <strong>Session Cookies:</strong> We use Session Cookies to
                operate our Service.
              </p>
            </li>
            <li>
              <p>
                <strong>Preference Cookies:</strong> We use Preference Cookies
                to remember your preferences and various settings.
              </p>
            </li>
            <li>
              <p>
                <strong>Security Cookies:</strong> We use Security Cookies for
                security purposes.
              </p>
            </li>
            <li>
              <p>
                <strong>Advertising Cookies:</strong> Advertising Cookies are
                used to serve you with advertisements that may be relevant to
                you and your interests.
              </p>
            </li>
          </ol>
          <ol start="5" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Use of Data</span>
                </strong>
              </p>
            </li>
          </ol>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              HEATHER TURANO COACHING, LLC uses the collected data for various
              purposes:
            </p>
          </blockquote>
          <ol type="a">
            <li>
              <p>to provide and maintain our Service;</p>
            </li>
            <li>
              <p>to notify you about changes to our Service;</p>
            </li>
            <li>
              <p>
                to allow you to participate in interactive features of our
                Service when you choose to do so;
              </p>
            </li>
            <li>
              <p>to provide customer support;</p>
            </li>
            <li>
              <p>
                to gather analysis or valuable information so that we can
                improve our Service;
              </p>
            </li>
            <li>
              <p>to monitor the usage of our Service;</p>
            </li>
            <li>
              <p>to detect, prevent and address technical issues;</p>
            </li>
            <li>
              <p>to fulfill any other purpose for which you provide it;</p>
            </li>
            <li>
              <p>
                to carry out our obligations and enforce our rights arising from
                any contracts entered into between you and us, including for
                billing and collection;
              </p>
            </li>
            <li>
              <p>
                to provide you with notices about your account and/or
                subscription, including expiration and renewal notices,
                email-instructions, etc.;
              </p>
            </li>
            <li>
              <p>
                to provide you with news, special offers and general information
                about other goods, services and events which we offer that are
                similar to those that you have already purchased or enquired
                about unless you have opted not to receive such information;
              </p>
            </li>
            <li>
              <p>
                in any other way we may describe when you provide the
                information;
              </p>
            </li>
            <li>
              <p>for any other purpose with your consent.</p>
            </li>
          </ol>
          <ol start="6" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Retention of Data</span>
                </strong>
              </p>
            </li>
          </ol>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              We will retain your Personal Data only for as long as is necessary
              for the purposes set out in this Privacy Policy. We will retain
              and use your Personal Data to the extent necessary to comply with
              our legal obligations (for example, if we are required to retain
              your data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies.
            </p>
            <p>
              We will also retain Usage Data for internal analysis purposes.
              Usage Data is generally retained for a shorter period, except when
              this data is used to strengthen the security or to improve the
              functionality of our Service, or we are legally obligated to
              retain this data for longer time periods.
            </p>
          </blockquote>
          <ol start="7" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Transfer of Data</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              Your information, including Personal Data, may be transferred to –
              and maintained on – computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
            </p>
            <p>
              If you are located outside United States and choose to provide
              information to us, please note that we transfer the data,
              including Personal Data, to United States and process it there.
            </p>
            <p>
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
            </p>
            <p>
              HEATHER TURANO COACHING, LLC will take all the steps reasonably
              necessary to ensure that your data is treated securely and in
              accordance with this Privacy Policy and no transfer of your
              Personal Data will take place to an organisation or a country
              unless there are adequate controls in place including the security
              of your data and other personal information.
            </p>
          </blockquote>
          <ol start="8" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Disclosure of Data</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We may disclose personal information that we collect, or you
              provide:
            </p>
          </blockquote>
          <ol type="a">
            <li>
              <p>
                <strong>Disclosure for Law Enforcement.</strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              Under certain circumstances, we may be required to disclose your
              Personal Data if required to do so by law or in response to valid
              requests by public authorities.
            </p>
          </blockquote>
          <ol start="2" type="a">
            <li>
              <p>
                <strong>Business Transaction.</strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              If we or our subsidiaries are involved in a merger, acquisition or
              asset sale, your Personal Data may be transferred.
            </p>
          </blockquote>
          <ol start="3" type="a">
            <li>
              <blockquote>
                <p>
                  <strong>
                    Other cases. We may disclose your information also:
                  </strong>
                </p>
              </blockquote>
              <ol type="i">
                <li>
                  <p>
                    for the purpose of including your company’s logo on our
                    website;
                  </p>
                </li>
                <li>
                  <p>with your consent in any other cases;</p>
                </li>
                <li>
                  <p>
                    if we believe disclosure is necessary or appropriate to
                    protect the rights, property, or safety of the Company, our
                    customers, or others.
                  </p>
                </li>
              </ol>
            </li>
          </ol>
          <ol start="9" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Security of Data</span>
                </strong>
              </p>
            </li>
          </ol>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              The security of your data is important to us but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>
          </blockquote>
          <ol start="10" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">
                    Your Data Protection Rights Under General Data Protection
                    Regulation (GDPR)
                  </span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              If you are a resident of the European Union (EU) and European
              Economic Area (EEA), you have certain data protection rights,
              covered by GDPR. – See more at
              https://eur-lex.europa.eu/eli/reg/2016/679/oj
            </p>
            <p>
              We aim to take reasonable steps to allow you to correct, amend,
              delete, or limit the use of your Personal Data.
            </p>
            <p>
              If you wish to be informed what Personal Data we hold about you
              and if you want it to be removed from our systems, please email us
              at support@heatherturanocoaching.com.
            </p>
            <p>
              In certain circumstances, you have the following data protection
              rights:
            </p>
          </blockquote>
          <ol type="a">
            <li>
              <p>
                the right to access, update or to delete the information we have
                on you;
              </p>
            </li>
            <li>
              <p>
                the right of rectification. You have the right to have your
                information rectified if that information is inaccurate or
                incomplete;
              </p>
            </li>
            <li>
              <p>
                the right to object. You have the right to object to our
                processing of your Personal Data;
              </p>
            </li>
            <li>
              <p>
                the right of restriction. You have the right to request that we
                restrict the processing of your personal information;
              </p>
            </li>
            <li>
              <p>
                the right to data portability. You have the right to be provided
                with a copy of your Personal Data in a structured,
                machine-readable and commonly used format;
              </p>
            </li>
            <li>
              <p>
                the right to withdraw consent. You also have the right to
                withdraw your consent at any time where we rely on your consent
                to process your personal information;
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              Please note that we may ask you to verify your identity before
              responding to such requests. Please note, we may not able to
              provide Service without some necessary data.
            </p>
            <p>
              You have the right to complain to a Data Protection Authority
              about our collection and use of your Personal Data. For more
              information, please contact your local data protection authority
              in the European Economic Area (EEA).
            </p>
          </blockquote>
          <ol start="11" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">
                    Your Data Protection Rights under the California Privacy
                    Protection Act (CalOPPA)
                  </span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              CalOPPA is the first state law in the nation to require commercial
              websites and online services to post a privacy policy. The law’s
              reach stretches well beyond California to require a person or
              company in the United States (and conceivable the world) that
              operates websites collecting personally identifiable information
              from California consumers to post a conspicuous privacy policy on
              its website stating exactly the information being collected and
              those individuals with whom it is being shared, and to comply with
              this policy. – See more at:
              https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
            </p>
            <p>According to CalOPPA we agree to the following:</p>
          </blockquote>
          <ol type="a">
            <li>
              <p>users can visit our site anonymously;</p>
            </li>
            <li>
              <p>
                our Privacy Policy link includes the word “Privacy”, and can
                easily be found on the page specified above on the home page of
                our website;
              </p>
            </li>
            <li>
              <p>
                users will be notified of any privacy policy changes on our
                Privacy Policy Page;
              </p>
            </li>
            <li>
              <p>
                users are able to change their personal information by emailing
                us at support@heatherturanocoaching.com.
              </p>
            </li>
          </ol>
          <blockquote>
            <p>Our Policy on “Do Not Track” Signals:</p>
            <p>
              We honor Do Not Track signals and do not track, plant cookies, or
              use advertising when a Do Not Track browser mechanism is in place.
              Do Not Track is a preference you can set in your web browser to
              inform websites that you do not want to be tracked.
            </p>
            <p>
              You can enable or disable Do Not Track by visiting the Preferences
              or Settings page of your web browser.
            </p>
          </blockquote>
          <ol start="12" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Service Providers</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We may employ third party companies and individuals to facilitate
              our Service (“<strong>Service Providers</strong>”), provide
              Service on our behalf, perform Service-related services or assist
              us in analysing how our Service is used.
            </p>
            <p>
              These third parties have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </p>
          </blockquote>
          <ol start="13" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Analytics</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We may use third-party Service Providers to monitor and analyze
              the use of our Service.
            </p>
            <p>
              <em>
                <strong>Piwik / Matomo</strong>
              </em>
            </p>
            <p>
              Piwik or Matomo is a web analytics service. You can visit their
              Privacy Policy page here: https://matomo.org/privacy-policy
            </p>
          </blockquote>
          <ol start="14" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">CI/CD tools</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              We may use third-party Service Providers to automate the
              development process of our Service.
            </p>
            <p>
              <strong>GitHub</strong>
            </p>
            <p>GitHub is provided by GitHub, Inc.</p>
            <p>
              GitHub is a development platform to host and review code, manage
              projects, and build software.
            </p>
            <p>
              For more information on what data GitHub collects for what purpose
              and how the protection of the data is ensured, please visit GitHub
              Privacy Policy page: <span className="underline"> </span>{" "}
              <a href="https://help.github.com/en/articles/github-privacy-statement">
                https://help.github.com/en/articles/github-privacy-statement.
              </a>
            </p>
          </blockquote>
          <ol start="15" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Payments</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We may provide paid products and/or services within Service. In
              that case, we use third-party services for payment processing
              (e.g. payment processors).
            </p>
            <p>
              We will not store or collect your payment card details. That
              information is provided directly to our third-party payment
              processors whose use of your personal information is governed by
              their Privacy Policy. These payment processors adhere to the
              standards set by PCI-DSS as managed by the PCI Security Standards
              Council, which is a joint effort of brands like Visa, Mastercard,
              American Express and Discover. PCI-DSS requirements help ensure
              the secure handling of payment information.
            </p>
            <p>The payment processors we work with are:</p>
            <p>Stripe:</p>
            <p>
              Their Privacy Policy can be viewed at:
              https://stripe.com/us/privacy
            </p>
          </blockquote>
          <ol start="16" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Links to Other Sites</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              Our Service may contain links to other sites that are not operated
              by us. If you click a third party link, you will be directed to
              that third party's site. We strongly advise you to review the
              Privacy Policy of every site you visit.
            </p>
          </blockquote>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
          </blockquote>
          <ol start="17" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Children's Privacy</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              Our Services are not intended for use by children under the age of
              18 (“<strong>Child</strong>” or “<strong>Children</strong>”).
            </p>
            <p>
              We do not knowingly collect personally identifiable information
              from Children under 18. If you become aware that a Child has
              provided us with Personal Data, please contact us. If we become
              aware that we have collected Personal Data from Children without
              verification of parental consent, we take steps to remove that
              information from our servers.
            </p>
          </blockquote>
          <ol start="18" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">
                    Changes to This Privacy Policy
                  </span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
            </p>
          </blockquote>
          <p>
            <span className="underline"> </span>
          </p>
          <blockquote>
            <p>
              We will let you know via email and/or a prominent notice on our
              Service, prior to the change becoming effective and update
              “effective date” at the top of this Privacy Policy.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </blockquote>
          <ol start="19" type="1">
            <li>
              <p>
                <strong>
                  <span className="underline">Contact Us</span>
                </strong>
              </p>
            </li>
          </ol>
          <blockquote>
            <p>
              <span className="underline"> </span>
            </p>
            <p>
              If you have any questions about this Privacy Policy, please
              contact us:
            </p>
            <p>By email: support@heatherturanocoaching.com.</p>
          </blockquote>
        </Content>
      </Section>
    </Layout>
  );
};

export default IndexPage;
