import Link from "next/link";
import React from "react";

import { FeaturePageComponent } from "../../../lib";
import { withHomePageLayout } from "./Home.layout";

export type HomePageProps = {
  categoryDocs: {
    content: string;
    data: {
      title: string;
      path: string[];
      [key: string]: unknown;
    };
    filePath: string;
  }[];
};

export const HomePage: FeaturePageComponent<HomePageProps> = ({
  categoryDocs
}) => {
  console.log(categoryDocs);
  return (
    <div>
      <h1>Home Page</h1>
      <p>Click the link below to navigate to a page generated by </p>
      <ul>
        {categoryDocs.map((doc) => (
          <li key={doc.filePath}>
            <Link href={`/${doc.data.path.join("/")}`}>
              <a>{doc.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

HomePage.withPageLayout = withHomePageLayout;
