services:
  # Design System
  - type: web
    name: Design System
    env: static
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    buildCommand: yarn build:components:storybook
    staticPublishPath: ./packages/components/storybook-static
    domains:
      - design.heatherturanocoaching.com
    envVars:
      - fromGroup: htc-npm

  # Websites
  # - type: web
  #   name: Website (PROD)
  #   env: static
  #   branch: master
  #   repo: https://github.com/heather-turano-coaching/heather-turano-coaching
  #   buildCommand: yarn build:website:prod
  #   staticPublishPath: ./packages/websites/next/out
  #   domains:
  #     - heatherturanocoaching.com
  #   envVars:
  #     - fromGroup: htc-npm
  #     - fromGroup: htc-ghost
  #     - fromGroup: htc-contentful
  #     - fromGroup: htc-stripe

  - type: web
    name: Website (DEV)
    env: node
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    buildCommand: yarn && yarn build:website:dev
    startCommand: yarn start:website:dev
    domains:
      - dev.heatherturanocoaching.com
    envVars:
      - fromGroup: htc-npm
      - fromGroup: htc-ghost
      - fromGroup: htc-contentful
      - fromGroup: htc-stripe

  - type: web
    name: 100 Days of Mindful Movement
    env: static
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    buildCommand: yarn build:mindful-movement
    staticPublishPath: ./packages/websites/mindful-movement/public
    domains:
      - mindfulmovement100.com
    envVars:
      - fromGroup: htc-npm
      - fromGroup: htc-contentful
      - fromGroup: htc-stripe
      - key: GATSBY_HTC_API
        value: https://api.heatherturanocoaching.com/graphql

  - type: web
    name: Packages
    env: static
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    buildCommand: yarn build:packages
    staticPublishPath: ./packages/websites/packages/public
    domains:
      - packages.heatherturanocoaching.com
    envVars:
      - fromGroup: htc-npm
      - fromGroup: htc-contentful
      - fromGroup: htc-stripe
      - key: GATSBY_HTC_API
        value: https://api.heatherturanocoaching.com/graphql

  # API
  - type: web
    name: Api
    env: node
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    # buildCommand: yarn && yarn build:api
    # Need to do this until there is a resolution on https://github.com/graphql-nexus/nexus/issues/1350
    startCommand: yarn serve:api
    domains:
      - api.heatherturanocoaching.com
    envVars:
      - fromGroup: htc-npm
      - fromGroup: htc-stripe
      - key: HTC_DB_CONNECTION_STRING
        fromDatabase:
          name: htc-db
          property: connectionString
      - key: HTC_MINDFUL_MOVEMENT_REDIRECT_ROOT_URL
        value: https://mindfulmovement100.com

  - type: web
    name: Ghost
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    domains:
      - blog.heatherturanocoaching.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://blog.heatherturanocoaching.com
      - key: mail__transport
        value: SMTP
      - key: mail__from
        value: "Heather Turano <me@heatherturanocoaching.com>"
      - key: mail__options__service
        value: SendGrid
      - key: mail__options__host
        value: smtp.sendgrid.net
      - key: mail__options__port
        value: 587
      - key: mail__options__auth__user
        value: apikey
      - key: mail__options__auth__pass
        sync: false

  - type: web
    name: Commento
    env: docker
    dockerfilePath: ./commento/Dockerfile
    dockerContext: ./commento
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    domains:
      - community.heatherturanocoaching.com
    envVars:
      - key: COMMENTO_ORIGIN
        value: https://community.heatherturanocoaching.com
      - key: COMMENTO_SMTP_HOST
        value: smtp.mailgun.org
      - key: COMMENTO_SMTP_PORT
        value: 587
      - key: COMMENTO_SMTP_USERNAME
        value: comments@mail.heatherturanocoaching.com
      - key: COMMENTO_SMTP_FROM_ADDRESS
        value: no-reply@heatherturanocoaching.com
      - key: COMMENTO_SMTP_PASSWORD
        sync: false
      - key: COMMENTO_POSTGRES
        fromDatabase:
          name: htc-commento-db-prod
          property: connectionString

databases:
  - name: htc-commento-db-prod
    databaseName: htc_commento_db_prod
    user: admin_prod
  - name: htc-db
    databaseName: htc_db
    user: admin

envVarGroups:
  - name: htc-ghost
    envVars:
      - key: GHOST_API_URL
        value: https://blog.heatherturanocoaching.com
      - key: GHOST_CONTENT_API_KEY
        sync: false
      - key: NEXT_PUBLIC_GHOST_API_URL
        sync: false
      - key: NEXT_PUBLIC_GHOST_CONTENT_API_KEY
        sync: false
  - name: htc-contentful
    envVars:
      - key: CONTENTFUL_HTC_SPACE_ID
        sync: false
      - key: CONTENTFUL_HTC_ACCESS_TOKEN
        sync: false
      - key: HTC_MINDFUL_MOVEMENT_CONTENTFUL_SPACE_ID
        sync: false
      - key: HTC_MINDFUL_MOVEMENT_CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: CONTENTFUL_HTC_MANAGEMENT_API_ACCESS_TOKEN
        sync: false
      - key: CONTENTFUL_HTC_ENVIRONMENT
        sync: false
  - name: htc-npm
    envVars:
      - key: FONTAWESOME_NPM_AUTH_TOKEN
        sync: false
  - name: htc-stripe
    envVars:
      - key: GATSBY_HTC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: HTC_STRIPE_SECRET_KEY
        sync: false
