services:
  # Blog
  - type: web
    name: Ghost
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: https://github.com/heather-turano-coaching/heather-turano-coaching
    domains:
      - blog.heatherturanocoaching.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://blog.heatherturanocoaching.com
      - key: mail__transport
        value: SMTP
      - key: mail__from
        value: "Heather Turano <me@heatherturanocoaching.com>"
      - key: mail__options__service
        value: SendGrid
      - key: mail__options__host
        value: smtp.sendgrid.net
      - key: mail__options__port
        value: 587
      - key: mail__options__auth__user
        value: apikey
      - key: mail__options__auth__pass
        sync: false

envVarGroups:
  - name: htc-ghost
    envVars:
      - key: NEXT_PUBLIC_HTC_GHOST_API_URL
        sync: false
      - key: NEXT_PUBLIC_HTC_GHOST_CONTENT_API_KEY
        sync: false
  - name: htc-contentful
    envVars:
      # new
      - key: HTC_CONTENTFUL_SPACE_ID
        sync: false
      - key: HTC_CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: HTC_CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN
        sync: false
      - key: HTC_CONTENTFUL_ENVIRONMENT
        sync: false
