services:
  - type: web
    name: HTC | Legacy | Website
    env: static
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    buildCommand: npm run bootstrap:ci && npm run build:legacy
    staticPublishPath: ./packages/legacy/public
    domains:
      - legacy.livelifemindful.com

  - type: web
    name: HTC | Live Life Mindful | Website
    env: static
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    buildCommand: npm run bootstrap:ci && npm run build:website
    staticPublishPath: ./packages/website/public
    domains:
      - dev.livelifemindful.com

  - type: web
    name: HTC | Live Life Mindful | Blog
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    domains:
      - blog.livelifemindful.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://blog.livelifemindful.com
      - key: mail__transport
        value: SMTP
      - key: mail__from
        value: "'Heather Turano' <heather@livelifemindful.com>"
      - key: mail__options__service
        value: Mailgun
      - key: mail__options__host
        value: smtp.mailgun.org
      - key: mail__options__port
        value: 465
      - key: mail__options__secureConnection
        value: true
      - key: mail__options__auth__user
        value: postmaster@mail.livelifemindful.com
      - key: mail__options__auth__pass
        sync: false

  - type: web
    name: HTC | Commento
    env: docker
    dockerfilePath: ./commento/Dockerfile
    dockerContext: ./commento
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    domains:
      - community.livelifemindful.com
    envVars:
      - key: COMMENTO_ORIGIN
        value: https://community.livelifemindful.com
      - key: COMMENTO_SMTP_HOST
        value: smtp.mailgun.org
      - key: COMMENTO_SMTP_PORT
        value: 587
      - key: COMMENTO_SMTP_USERNAME
        value: postmaster@mail.livelifemindful.com
      - key: COMMENTO_SMTP_FROM_ADDRESS
        value: "'Heather Turano' <heather@livelifemindful.com>"
      - key: COMMENTO_SMTP_PASSWORD
        sync: false
      - key: COMMENTO_POSTGRES
        fromDatabase:
          name: htc-commento-db-prod
          property: connectionString

databases:
  - name: htc-commento-db-prod
    databaseName: htc_commento_db_prod
    user: admin_prod
