services:
  - type: web
    name: htc-ghost
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/website.git
    domains:
      - https://ghost.heatherturanocoaching.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://ghost.heatherturanocoaching.com

  - type: web
    name: htc-commento
    env: docker
    dockerfilePath: ./commento/Dockerfile
    dockerContext: ./commento
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/website.git
    domains:
      - https://community.heatherturanocoaching.com
    envVars:
      - key: COMMENTO_ORIGIN
        value: https://community.heatherturanocoaching.com
      - key: COMMENTO_POSTGRES
        fromDatabase:
          name: htc-commento-db-prod
          property: connectionString

databases:
  - name: htc-commento-db-prod
    databaseName: htc_commento_db_prod
    user: admin_prod
