services:
  - type: web
    name: HTC | Live Life Mindful | Blog (Static)
    env: static
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    buildCommand: npm run bootstrap:ci && npm run build:blog
    staticPublishPath: ./packages/blog/public
    domains:
      - blog.livelifemindful.com
    envVars:
      - fromGroup: npm
      - key: GHOST_API_URL
        sync: false
      - key: GHOST_CONTENT_API_KEY
        sync: false
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: COMMENTO_ORIGIN
        sync: false
      - key: SERVERLESS_API
        value: https://api.livelifemindful.com

  - type: web
    name: HTC | Live Life Mindful | Design
    env: static
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    buildCommand: npm run bootstrap:ci && npm run build:components:storybook
    staticPublishPath: ./packages/components/storybook-static
    domains:
      - design.livelifemindful.com
    envVars:
      - fromGroup: npm

  - type: web
    name: HTC | Live Life Mindful | Blog (CMS)
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    domains:
      - admin.blog.livelifemindful.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://admin.blog.livelifemindful.com
      - key: mail__transport
        value: SMTP
      - key: mail__from
        value: "'Heather Turano' <heather@livelifemindful.com>"
      - key: mail__options__service
        value: Mailgun
      - key: mail__options__host
        value: smtp.mailgun.org
      - key: mail__options__port
        value: 465
      - key: mail__options__secureConnection
        value: true
      - key: mail__options__auth__user
        value: postmaster@mail.livelifemindful.com
      - key: mail__options__auth__pass
        sync: false

  - type: web
    name: HTC | Live Life Mindful | Blog (Comments)
    env: docker
    dockerfilePath: ./commento/Dockerfile
    dockerContext: ./commento
    branch: master
    repo: https://gitlab.com/imaginedelements/heather-turano-coaching/live-life-mindful.git
    domains:
      - community.blog.livelifemindful.com
    envVars:
      - key: COMMENTO_ORIGIN
        value: https://community.blog.livelifemindful.com
      - key: COMMENTO_SMTP_HOST
        value: smtp.mailgun.org
      - key: COMMENTO_SMTP_PORT
        value: 587
      - key: COMMENTO_SMTP_USERNAME
        value: postmaster@mail.livelifemindful.com
      - key: COMMENTO_SMTP_FROM_ADDRESS
        value: "'Heather Turano' <heather@livelifemindful.com>"
      - key: COMMENTO_SMTP_PASSWORD
        sync: false
      - key: COMMENTO_POSTGRES
        fromDatabase:
          name: htc-commento-db-prod
          property: connectionString

databases:
  - name: htc-commento-db-prod
    databaseName: htc_commento_db_prod
    user: admin_prod
