declare namespace NodeJS {
  export interface ProcessEnv {
    // ghost
    NEXT_PUBLIC_HTC_GHOST_API_CONTENT_VERSION: string;
    NEXT_PUBLIC_HTC_GHOST_API_CONTENT_KEY: string;
    NEXT_PUBLIC_HTC_GHOST_API_ADMIN_VERSION: string;
    NEXT_PUBLIC_HTC_GHOST_API_ADMIN_KEY: string;
    NEXT_PUBLIC_HTC_GHOST_API_URL: string;
    // contentful
    HTC_CONTENTFUL_API_MANAGEMENT_ACCESS_TOKEN: string;
    HTC_CONTENTFUL_API_CONTENT_ACCESS_TOKEN: string;
    HTC_CONTENTFUL_API_PREVIEW_ACCESS_TOKEN: string;
    HTC_CONTENTFUL_ENVIRONMENT: string;
    HTC_CONTENTFUL_SPACE_ID: string;
    HTC_CONTENTFUL_PREVIEW_SECRET: string;
    // eventbrite
    HTC_EVENTBRITE_API_KEY: string;
    HTC_EVENTBRITE_CLIENT_SECRET: string;
    HTC_EVENTBRITE_PRIVATE_TOKEN: string;
    HTC_EVENTBRITE_PUBLIC_TOKEN: string;
    HTC_EVENTBRITE_ORG_ID: string;
  }
}
