import fs from "fs";
import path from "path";

import matter from "gray-matter";
import Link from "next/link";

import { DOCS_PATH, docsFilePath } from "../lib";

export function getStaticProps() {
  const posts = docsFilePath.map((filePath) => {
    const source = fs.readFileSync(path.join(DOCS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath
    };
  });

  return { props: { posts } };
}

const Page = ({}) => {
  return (
    <>
      <h1>Home Page</h1>
      <p>Click the link below to navigate to a page generated by </p>
      <ul>
        {docs.map((doc) => (
          <li key={doc.filePath}>
            <Link
              as={`/components/${doc.filePath.replace(/\.mdx?$/, "")}`}
              href={`/components/[slug]`}
            >
              <a>{doc.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
};

export default Page;
